services:
  postgres:
    image: postgres:15
    container_name: faceclinic-db
    environment:
      POSTGRES_DB: faceclinicdb
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - clinic-net

  backend:
    build: .
    container_name: faceclinic-api
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - clinic-net

volumes:
  pgdata:

networks:
  clinic-net: