spring:
  security:
    user:
      name: user
      password: 12345
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  liquibase:
    enabled: true
    change-log: db/changelog/master.xml
    contexts: none
  data:
    rest:
      default-media-type: application/json
  hateoas:
    use-hal-as-default-json-media-type: false
  mvc:
    converters:
      preferred-json-mapper: jackson

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  resources:
    static-locations: classpath:/static/
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML
      encoding: UTF-8
      cache: false

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE