spring:
  security:
    user:
      name: user
      password: 12345
  liquibase:
    enabled: true
    change-log: db/changelog/master.xml
    contexts: none
  datasource:
    url: jdbc:postgresql://localhost:5432/faceclinicdb
    username: admin
    password: postgres
    driver-class-name: org.postgresql.Driver
    resources:
      static-locations: classpath:/static/
      thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        mode: HTML
        encoding: UTF-8
        cache: false

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect


